services:
  db:
    image: postgres:15
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  backend:
    build: ../backend
    command: >-
      bash -c "python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
    working_dir: /app
    volumes:
      - ../backend:/app
    env_file:
      - ../.env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
  frontend:
    build: ../frontend
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    volumes:
      - ../frontend:/app
      - /app/node_modules
    env_file:
      - ../.env
    depends_on:
      - backend
    ports:
      - "3000:3000"
volumes:
  postgres_data:
