name: CI Build & Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports: [5432:5432]
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Install test dependencies
        run: |
          cd backend
          pip install pytest pytest-django pytest-cov

      - name: Run backend tests
        run: |
          cd backend
          pytest --cov=. -q

      - name: Build Docker images
        run: |
          docker compose -f infra/docker-compose.yml build
